baseurl = "https://rabinadhikari.com.np/"
title = "Rabin Adhikari"

theme = "hugo-coder"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "rabinadk1"
googleAnalytics = "UA-176075966-1"

[params]
    author = "Rabin Adhikari"
    description = "Rabin Adhikari's personal site"
    keywords = "blog,developer,personal"
    info = "Full Stack Developer, Deep Learning Enthusiast, and Magician"
    avatarurl = "images/avatar.webp"
    images = ["images/avatar.webp"] # for og and twitter
    # gravatar = "john.doe@example.com"
    footercontent = "Looking for an interesting project to work on"

    dateformat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hidecolorschemetoggle = false
        
    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = false

    # Custom CSS
    custom_css = []

    # Custom JS
    custom_js = []

# If you want to use fathom(https://usefathom.com) for analytics, add this section
# [params.fathomAnalytics]
#     siteID = "ABCDE"
    # Default value is cdn.usefathom.com, overwrite this if you are self-hosting
#     serverURL = "analytics.example.com"

# If you want to use plausible(https://plausible.io) for analytics, add this section
# [params.plausibleAnalytics]
#     domain = "example.com"
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
#     serverURL = "analytics.example.com"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/rabinadk1/"
[[params.social]]
    name = "Gitlab"
    icon = "fa fa-gitlab"
    weight = 2
    url = "https://gitlab.com/rabinadk1"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 3
    url = "https://twitter.com/rabinadk1/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/rabinadk1/"
[[params.social]]
    name = "RSS"
    icon = "fa fa-rss"
    weight = 5
    url = "https://rabinadhikari.com.np/index.xml"
    rel = "alternate"
    type = "application/rss+xml"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"


    [languages.ne]
        languagename = "Nepali"
        title = "रबिन अधिकारी"

        [languages.ne.params]
            author = "रबिन अधिकारी"
            info = "पूर्ण स्ट्याक विकासकर्ता, डीप लर्निंग उत्साहित एवं जादूगर"
            keywords = "ब्लग, विकासकर्ता, व्यक्तिगत"
            description = "रबिन अधिकारीको व्यक्तिगत साइट"
            footercontent = "कामका लागि ईन्टर्स्टिंग परियोजनाको खोजी गर्दै"

        [languages.ne.menu]

            [[languages.ne.menu.main]]
            name = "बारेमा"
            weight = 1
            url = "about/"

            [[languages.ne.menu.main]]
            name = "ब्लग"
            weight = 2
            url = "posts/"

            [[languages.ne.menu.main]]
            name = "परियोजनाहरु"
            weight = 3
            url = "projects/"

            [[languages.ne.menu.main]]
            name = "मलाई सम्पर्क गर्नुहोस्"
            weight = 5
            url = "contact/"
