baseUrl = "https://rabinadhikari.com.np/"
title = "Rabin Adhikari"

theme = "hugo-coder"

languageCode = "en"
defaultContentLanguage = "en"

paginate = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = "rabinadk1"
googleAnalytics = "UA-176075966-1"

[params]
    author = "Rabin Adhikari"
    description = "Rabin Adhikari's personal site"
    keywords = "blog,developer,personal"
    info = "Full Stack Developer, Deep Learning Enthusiast, and Magician"
    avatarUrl = "images/avatar.webp"
    images = ["images/avatar.webp"] # for og and twitter
    # gravatar = "john.doe@example.com"
    footerContent = "Looking for an interesting project to work on"

    dateFormat = "January 2, 2006"

    hideFooter = false
    hideCredits = false
    hideCopyright = false
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    # Enable the Right To Left mode.
    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = false

    # Custom CSS
    customCSS = ["css/center.css"]

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

# If you want to implement a Content-Security-Policy, add this section
[params.csp]
	  childsrc = ["'self'"]
	  fontsrc = [
        "'self'",
		    "https://fonts.gstatic.com",
		    "https://cdn.jsdelivr.net/"
    ]
	  formaction = ["'self'"]
	  framesrc = ["'self'"]
	  imgsrc = ["'self'"]
	  objectsrc = ["'none'"]
	  stylesrc = [
        "'self'",
		    "'unsafe-inline'",
		    "https://fonts.googleapis.com/",
		    "https://cdn.jsdelivr.net/"
    ]
	  scriptsrc = [
        "'self'",
		    "'unsafe-inline'",
            "https://ajax.cloudflare.com",
		    "https://www.google-analytics.com"
    ]
	  prefetchsrc = ["'self'"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Email"
    icon = "fa fa-send"
    weight = 1
    url = "mailto:rabin.adk1@gmail.com"
[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 2
    url = "https://github.com/rabinadk1/"
[[params.social]]
    name = "Gitlab"
    icon = "fa fa-gitlab"
    weight = 3
    url = "https://gitlab.com/rabinadk1"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 4
    url = "https://twitter.com/rabinadk1/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 5
    url = "https://www.linkedin.com/in/rabinadk1/"
[[params.social]]
    name = "RSS"
    icon = "fa fa-rss"
    weight = 6
    url = "https://rabinadhikari.com.np/index.xml"
    rel = "alternate"
    type = "application/rss+xml"


[languages]
    [languages.en]
        languageName = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 3
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"


    [languages.ne]
        languageName = "Nepali"
        title = "रबिन अधिकारी"

        [languages.ne.params]
            author = "रबिन अधिकारी"
            info = "पूर्ण स्ट्याक विकासकर्ता, डीप लर्निंग उत्साहित एवं जादूगर"
            keywords = "ब्लग, विकासकर्ता, व्यक्तिगत"
            description = "रबिन अधिकारीको व्यक्तिगत साइट"
            footerContent = "कामका लागि ईन्टर्स्टिंग परियोजनाको खोजी गर्दै"

        [languages.ne.menu]

            [[languages.ne.menu.main]]
            name = "बारेमा"
            weight = 1
            url = "about/"

            [[languages.ne.menu.main]]
            name = "ब्लग"
            weight = 2
            url = "posts/"

            [[languages.ne.menu.main]]
            name = "प्रोजेक्टहरू"
            weight = 3
            url = "projects/"

            [[languages.ne.menu.main]]
            name = "मलाई सम्पर्क गर्नुहोस्"
            weight = 5
            url = "contact/"
